export default {
  LOGIN: 'LOGIN',
  SETTINGS: 'SETTINGS',
  CITY_SELECTION: 'CITY_SELECTION',
  DAY_SELECTION: 'DAY_SELECTION',
  WEATHER: 'WEATHER',
  FORECAST: 'FORECAST',
  WEATHER_STACK: 'WEATHER_STACK',
};
